### ISSUE TITLE
Census projections

### ISSUE THREAD

**Issue by wilson428** [unitedstates/wish-list#8]
Any interest in Census population projections fetcher? I have scripts to download and organize the [2012-2060 projections](http://www.census.gov/population/projections/) either by cohort (everyone born in 1975 over time) or static age (number of 75-year-olds every year), for any combination of gender, ethnicity and race. 

[What the data looks like.](http://experimentsinform.com/projects/census-projections-lifelines/)

Could be expanded down the line for other Census sets, if such a thing doesn't exist elsewhere.

**Comment by konklone** [comment]
I think @jcarbaugh has done something like this.

**Comment by JoshData** [comment]
Hey. I think that might be a little out of the scope of this github org. My sense is we're basically gathering legal artifacts, rather than, say, the outputs of government agencies. Otherwise this org could grow into thousands of projects. Just my two cents. The data is very cool though.

**Comment by wilson428** [comment]
No problem at all! Will close this.

**Comment by konklone** [comment]
I totally agree about not wanting to include every agency, and having too many repos. But I'd use the criteria of "foundational" rather than legal. This is why I brought in @jcarbaugh's python-us - a basic tool if you work with core data of the United States.  And We the People, regardless of what you think of its substance, is the White House's central place for channeling and responding to the public.

So I'd really like to see some Census parsers here. It's maybe the single broadest and most important dataset of any agency at all, and is useful in a huge variety of contexts, including analyzing Congressional districts and representation. It's a fundamental dataset of the United States.

**Comment by wilson428** [comment]
Makes sense to me, fwiw. Don't you guys have an API for this already? 
https://github.com/sunlightlabs/census

**Comment by konklone** [comment]
It's a wrapper for the official API, but yeah.

**Comment by jcarbaugh** [comment]
Despite being mentioned numerous times, I'm finally seeing this thread. Sorry! @wilson428 would you mind opening a ticket on https://github.com/sunlightlabs/census? Not sure if this is something that can be included in an API client, but we should see how it might fit in.

**Comment by wilson428** [comment]
Sure thing
